export const settings={
    maximumBoxes:300,
    bombTimer:3,
    initialLimit:100,
    playerGraphic:"😎",
    guardGraphic:"👮‍♂️",
    initialExplosionGraphic:"💥",
    boxGraphic:"X",
     explosionEffect : "/hq-explosion-6288.mp3",
     startGameEffect : "/wrong-place-129242.mp3",
     guardDie :"/pretty-sure-i-just-died-103109.mp3",
     playerDie : "/manx27s-cry-122258.mp3",
      gameSpeed : 200,
     shotDistance : 4,
     difficulty:5,
     boardWidth:32,
     boardHeight:21,
     initup:"k",
     initdown:"m",
     initleft:"z",
     initright:"x",
     initfire:"l"
}